domain: chorda3.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: http://chorda3.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /chorda-docs/      # place folder name if the site is served in a subfolder